
PROJECT:
  CONFIG_DIR: "erc/config/exp_cp"

MODEL:
  TYPE: erm
  DIR: "./models/fmow_models/fmow_ERM-train_update_iter=3000-lr=0.0001-mini_batch_size=64-seed=1-offline_time=13"

EXP:
  EPS: 0.1
  DELTA: 0.1
  NR_TRIALS: 10
  NR_TIMESTEPS: 1500
  BATCH_TIMESTEP: 1
  PSI_START: 0.0
  PSI_END: 1.0
  PSI_INIT: 1.0
  PSI_STEP: 0.01
  RISK: miscover
  BET_TYPE: approx_grapa # [unit_bet, approx_grapa, grapa]
  NR_POINT_RISK_SAMP: 1000
  NR_BURNIN: 100
  TRACKER_WINDOW: # [point_risk, running_risk, eprocess]
    - 0
    - 0
    - 0
  STOP_COUNTER: # [point_risk, running_risk, eprocess]
    - 0
    - 0
    - 0
  SPLIT_TIME: 10
  SET_SCORE: probs


  # run cmd
  # python erc/exp/exp_cp.py --cfg_dir="erc/config/exp_cp" --exp_suffix="_TEST1" --get_pred --save_file --batch_ts=1 --tracker_window 0 0 0 --stop_counter 5 25 0 --device="cuda"